name: lms_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.7.6+52

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  extended_nested_scroll_view: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_widget_from_html: ^0.15.1
  
  firebase_core_platform_interface: ^5.0.0

  loading_skeleton_niu: ^0.0.1
  http_auth: ^1.0.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4  

  persistent_bottom_nav_bar:
    git:
      url: https://github.com/HamzaSamirAmmar/PersistentBottomNavBar.git
  stripe_sdk:
    git: https://github.com/cmtboy/stripe-sdk

  url_launcher: ^6.3.0
  percent_indicator: ^4.2.3
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.1
  razorpay_flutter: ^1.3.7

  open_document: ^1.0.7
  paytm_allinonesdk:
    git: https://github.com/cmtboy/paytm_allinonesdk-1.2.6

  flutter_facebook_auth: ^7.0.0
  google_sign_in: ^6.2.1
  connection_notifier: ^2.0.1
  flutter_inappwebview: ^6.0.0
  sn_progress_dialog: ^1.1.4

  vdocipher_flutter: ^2.6.6

  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master

  eko_jitsi:
    path: eko-jitsi

  fancy_shimmer_image:
    path: fancy-shimmer-image
  flutter_blurhash: ^0.8.2
  purchases_flutter: ^6.30.0
  youtube_player_flutter: ^9.0.1
  flutter_slidable: ^3.1.0

  google_fonts: ^6.2.1
  awesome_notifications: ^0.9.3+1
  file_picker: ^8.0.3
  reactive_forms: ^17.0.1
  open_file: ^3.3.2
  chewie: ^1.8.3
  video_player: ^2.9.1
  pdfrx: ^1.0.83
  device_info_plus: ^10.1.2

dependency_overrides:
  win32: ^5.5.4
  http: ^0.13.5
  archive: ^3.6.1

  webview_flutter: ^4.8.0
  webview_flutter_android: 3.16.1

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  import_sorter: ^4.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpg"

flutter_native_splash:
  background_image: "images/Splash.png"
  fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: AvenirNext
      fonts:
        - asset: font/AvenirNextLTPro-Regular.otf